# Tensor Manipulation

In [1]:
import numpy as np

In [2]:
t = np.array([0.,1.,2.,3.,4.,5.,6.])

In [3]:
print(t.ndim) # print rank

1


In [4]:
print(t.shape) # print shape

(7,)


In [5]:
print(t[0], t[1], t[-1]) # t의 첫번째, 두번째, 마지막 element

0.0 1.0 6.0


In [7]:
print(t[2:5], t[4:-1]) # 2번째에서 4번째, 4번째에서 마지막전까지

[2. 3. 4.] [4. 5.]


In [9]:
print(t[:2], t[3:]) # 첫번째부터 세번째 전까지, 세번째부터 마지막까지

[0. 1.] [3. 4. 5. 6.]


## 2D array

In [10]:
t = np.array([[1., 2., 3.], [4., 5., 6.], [7., 8., 9.], [10., 11., 12.]])

In [12]:
print(t.ndim) # rank

2


In [13]:
print(t.shape) # shape

(4, 3)


In [14]:
import tensorflow as tf
import pprint

pp = pprint.PrettyPrinter(indent=4)
sess = tf.InteractiveSession()

C:\Users\MJ\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


# Shape, Rank, Axis

In [15]:
t = tf.constant([1,2,3,4])
tf.shape(t).eval()

array([4])

In [17]:
t = tf.constant([[1,2],[3,4]])
tf.shape(t).eval()

array([2, 2])

In [18]:
t = tf.constant([[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],[[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]])
tf.shape(t).eval()

array([1, 2, 3, 4])

In [19]:
# shape= ( # , @ )  @파악은 대괄호 가장 마지막에 들어있는 element의 수를 파악

In [20]:
# [] 수에 따라 shape( , , , ) 가 정해짐

In [21]:
# 괄호 수별로 각각 안에 몇개가 들었는지를 파악하면 이해하기 편함

In [22]:

[
    [
        [
            [1,2,3,4], 
            [5,6,7,8],
            [9,10,11,12]
        ],
        [
            [13,14,15,16],
            [17,18,19,20], 
            [21,22,23,24]
        ]
    ]
]

[[[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
  [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]]]

In [23]:
# 위 array의 shape = ( 1, 2, 3, 4)
# 위 array의 rank = 4
# 위 array의 Axis = 4인데 가장 바깥쪽부터 0으로 시작

In [29]:
matrix1 = tf.constant([[1., 2.], [3.,4.]]) # shape = (2 , 2)
matrix2 = tf.constant([[1.],[2.]]) # shape = (2, 1)
tf.matmul(matrix1, matrix2).eval()

array([[ 5.],
       [11.]], dtype=float32)

In [30]:
(matrix1*matrix2).eval() # 일반적인 matrix 곱을 하면 이렇게 됨

array([[1., 2.],
       [6., 8.]], dtype=float32)

# Broadcasting
- shape이 다르더라도 연산이 가능하게 해주는 기능
- 연산시에 shape 고려할것!!

In [31]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2.],[2.]])
(matrix1+matrix2).eval()

array([[5., 5.],
       [5., 5.]], dtype=float32)

In [32]:
matrix1 = tf.constant([[3., 3.]])
matrix2 = tf.constant([[2., 2.]])
(matrix1+matrix2).eval()

array([[5., 5.]], dtype=float32)

# Reduce mean

In [33]:
tf.reduce_mean([1,2], axis=0).eval()

1

In [35]:
x = [[1.,2.], [3.,4.]] # -> 방향은 axis = 1, 화살표 아래방향은 axis=0

In [40]:
tf.reduce_mean(x).eval() # axis 지정 안하면 모두를 평균내라!

2.5

In [37]:
tf.reduce_mean(x, axis=0).eval()

array([2., 3.], dtype=float32)

In [38]:
tf.reduce_mean(x, axis=1).eval()

array([1.5, 3.5], dtype=float32)

In [39]:
tf.reduce_mean(x, axis=-1).eval()

array([1.5, 3.5], dtype=float32)

In [41]:
x = [[1.,2.], [3.,4.]]

In [43]:
tf.reduce_sum(x).eval()

10.0

In [44]:
tf.reduce_sum(x, axis=0).eval()

array([4., 6.], dtype=float32)

In [45]:
tf.reduce_sum(x, axis=-1).eval()

array([3., 7.], dtype=float32)

In [46]:
tf.reduce_mean(tf.reduce_sum(x, axis=-1)).eval()

5.0

In [48]:
x = [[0,1,2],[2,1,0]]

In [49]:
tf.argmax(x, axis=0).eval()

array([1, 0, 0], dtype=int64)

In [50]:
tf.argmax(x, axis=1).eval()

array([2, 0], dtype=int64)

In [51]:
tf.argmax(x, axis=-1).eval()

array([2, 0], dtype=int64)

In [52]:
# argmax 개념 이해 = http://gomguard.tistory.com/145 참고

# Reshape

In [53]:
t = np.array([[[0, 1, 2], 
               [3, 4, 5]],
              
              [[6, 7, 8], 
               [9, 10, 11]]])
t.shape

(2, 2, 3)

In [54]:
tf.reshape(t, shape=[-1, 3]).eval()

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [55]:
tf.reshape(t, shape=[-1, 1, 3]).eval()

array([[[ 0,  1,  2]],

       [[ 3,  4,  5]],

       [[ 6,  7,  8]],

       [[ 9, 10, 11]]])

## Reshape(squeeze, expand)

In [56]:
tf.squeeze([[0], [1], [2]]).eval() # 각각 나눠져 있던 shape을 합쳐줌

array([0, 1, 2])

In [57]:
tf.expand_dims([0, 1, 2], 1).eval() # 합쳐져 있던 shape을 펴줌

array([[0],
       [1],
       [2]])

# One hot

In [59]:
tf.one_hot([[0], [1], [2], [0]], depth=3).eval()
# depth를 통해 몇개인지 지정
# one hot encoding을 하면 rank가 하나 증가함

array([[[1., 0., 0.]],

       [[0., 1., 0.]],

       [[0., 0., 1.]],

       [[1., 0., 0.]]], dtype=float32)

In [60]:
t = tf.one_hot([[0], [1], [2], [0]], depth=3)
tf.reshape(t, shape=[-1, 3]).eval()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]], dtype=float32)

# Casting

In [61]:
tf.cast([1.8, 2.2, 3.3, 4.9], tf.int32).eval()
# float을 int로 변경
# Accuracy 구할 때 사용

array([1, 2, 3, 4])

In [62]:
tf.cast([True, False, 1 == 1, 0 == 1], tf.int32).eval()

array([1, 0, 1, 0])

# Stack

In [63]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z]).eval()

array([[1, 4],
       [2, 5],
       [3, 6]])

In [64]:
x = [1, 4]
y = [2, 5]
z = [3, 6]

# Pack along first dim.
tf.stack([x, y, z], axis=1).eval()

array([[1, 2, 3],
       [4, 5, 6]])

# Ones and Zeros like

In [66]:
# 어떤 array가 주여졌을 때, 그것과 같은 shape으로 
# elelment가 모두 0 혹은 1인 array를 생성하는 방법

In [67]:
x = [[0, 1, 2],
     [2, 1, 0]]

tf.ones_like(x).eval()

array([[1, 1, 1],
       [1, 1, 1]])

In [69]:
tf.zeros_like(x).eval()

array([[0, 0, 0],
       [0, 0, 0]])

# Zip

In [70]:
for x, y in zip([1, 2, 3], [4, 5, 6]):
    print(x, y)

1 4
2 5
3 6


In [71]:
for x, y, z in zip([1, 2, 3], [4, 5, 6], [7, 8, 9]):
    print(x, y, z)

1 4 7
2 5 8
3 6 9


# Transpose

In [72]:
t = np.array([[[0, 1, 2], [3, 4, 5]], [[6, 7, 8], [9, 10, 11]]])
pp.pprint(t.shape)
pp.pprint(t)

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [73]:
t1 = tf.transpose(t, [1, 0, 2])
pp.pprint(sess.run(t1).shape)
pp.pprint(sess.run(t1))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 6,  7,  8]],

       [[ 3,  4,  5],
        [ 9, 10, 11]]])


In [74]:
t = tf.transpose(t1, [1, 0, 2])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])


In [76]:
t2 = tf.transpose(t, [1, 2, 0])
pp.pprint(sess.run(t2).shape)
pp.pprint(sess.run(t2))

(2, 3, 2)
array([[[ 0,  6],
        [ 1,  7],
        [ 2,  8]],

       [[ 3,  9],
        [ 4, 10],
        [ 5, 11]]])


In [77]:
t = tf.transpose(t2, [2, 0, 1])
pp.pprint(sess.run(t).shape)
pp.pprint(sess.run(t))

(2, 2, 3)
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])
