In [2]:
import tensorflow as tf
tf.set_random_seed(207) # for reproducibility

C:\Users\MJ\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


In [3]:
x1_data = [73.,93.,89.,96.,73.]
x2_data = [80.,88.,91.,98.,66.]
x3_data = [75.,93.,90.,100.,70.]

In [4]:
y_data = [152.,185.,180.,196.,142.]

In [5]:
# placeholders for a tensor that will be always fed.
x1 = tf.placeholder(tf.float32)
x2 = tf.placeholder(tf.float32)
x3 = tf.placeholder(tf.float32)

In [6]:
Y = tf.placeholder(tf.float32)

In [7]:
w1 = tf.Variable(tf.random_normal([1]), name='weight1')
w2 = tf.Variable(tf.random_normal([1]), name='weight2')
w3 = tf.Variable(tf.random_normal([1]), name='weight3')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [8]:
hypothesis = x1 * w1 + x2 * w2 + x3 * w3 + b

In [9]:
# cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [10]:
# Minimize. Need a very small learning rate for this data set
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [11]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [12]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run([cost, hypothesis, train],
                                   feed_dict={x1: x1_data, x2: x2_data, x3: x3_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  74777.06 
Prediction:
 [ -80.589905 -113.884796 -103.03302  -116.147804  -88.02435 ]
10 Cost:  46.489086 
Prediction:
 [161.21121 176.79161 183.34962 195.71913 133.69804]
20 Cost:  45.5627 
Prediction:
 [161.91669 177.689   184.20808 196.65735 134.39198]
30 Cost:  45.3219 
Prediction:
 [161.89278 177.70953 184.20264 196.65482 134.41708]
40 Cost:  45.082417 
Prediction:
 [161.86671 177.72734 184.19458 196.64944 134.4401 ]
50 Cost:  44.844185 
Prediction:
 [161.84073 177.74513 184.18658 196.6441  134.46306]
60 Cost:  44.60734 
Prediction:
 [161.8148  177.76283 184.17857 196.63878 134.48593]
70 Cost:  44.371716 
Prediction:
 [161.78897 177.78053 184.17061 196.63344 134.50876]
80 Cost:  44.13725 
Prediction:
 [161.76315 177.79814 184.16263 196.6281  134.53151]
90 Cost:  43.904198 
Prediction:
 [161.73747 177.81575 184.15472 196.62285 134.55423]
100 Cost:  43.672356 
Prediction:
 [161.7118  177.83327 184.14679 196.61757 134.57684]
110 Cost:  43.441677 
Prediction:
 [161.68623 177.8

960 Cost:  27.771229 
Prediction:
 [159.74542 179.17747 183.53934 196.21613 136.30885]
970 Cost:  27.626379 
Prediction:
 [159.72511 179.19135 183.53308 196.21202 136.32669]
980 Cost:  27.482327 
Prediction:
 [159.70488 179.20517 183.5268  196.20795 136.34448]
990 Cost:  27.3391 
Prediction:
 [159.68468 179.21895 183.52055 196.20386 136.3622 ]
1000 Cost:  27.196615 
Prediction:
 [159.66457 179.23273 183.51434 196.19978 136.3799 ]
1010 Cost:  27.054926 
Prediction:
 [159.64449 179.24644 183.50813 196.19574 136.39752]
1020 Cost:  26.913916 
Prediction:
 [159.62445 179.26013 183.50194 196.19168 136.41512]
1030 Cost:  26.77367 
Prediction:
 [159.60448 179.27377 183.49576 196.18765 136.43268]
1040 Cost:  26.634201 
Prediction:
 [159.58455 179.28738 183.4896  196.18362 136.45016]
1050 Cost:  26.495502 
Prediction:
 [159.56468 179.30096 183.48347 196.17963 136.46762]
1060 Cost:  26.357508 
Prediction:
 [159.54486 179.31451 183.47733 196.17563 136.485  ]
1070 Cost:  26.220285 
Prediction:
 [15

1910 Cost:  16.980461 
Prediction:
 [158.04102 180.34172 183.01176 195.87561 137.80206]
1920 Cost:  16.893732 
Prediction:
 [158.0253  180.3525  183.0069  195.87254 137.81581]
1930 Cost:  16.807571 
Prediction:
 [158.00961 180.36319 183.00204 195.86945 137.8295 ]
1940 Cost:  16.721725 
Prediction:
 [157.99396 180.37389 182.99718 195.86636 137.84317]
1950 Cost:  16.636469 
Prediction:
 [157.97835 180.38452 182.99234 195.86327 137.85678]
1960 Cost:  16.551601 
Prediction:
 [157.9628  180.39517 182.98752 195.86023 137.87038]
1970 Cost:  16.467215 
Prediction:
 [157.94727 180.40575 182.9827  195.85716 137.88393]
1980 Cost:  16.3833 
Prediction:
 [157.93178 180.41632 182.9779  195.85413 137.89742]
1990 Cost:  16.299814 
Prediction:
 [157.91634 180.42685 182.9731  195.85107 137.91089]
2000 Cost:  16.216825 
Prediction:
 [157.90097 180.43738 182.96835 195.84807 137.92435]


In [2]:
import tensorflow as tf
tf.set_random_seed(207)  # for reproducibility

In [3]:

x_data = [[73., 80., 75.],
          [93., 88., 93.],
          [89., 91., 90.],
          [96., 98., 100.],
          [73., 66., 70.]]
y_data = [[152.],
          [185.],
          [180.],
          [196.],
          [142.]]


# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 3])
# shape 설정시에 앞에는 데이터 개수, 뒤에는 한 데이터에 들은 instance 개수
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([3, 1]), name='weight')
# x shape * W shape = Y shape 이므로 그걸 계산해서 shape 설정해줘야함.
b = tf.Variable(tf.random_normal([1]), name='bias')

# Hypothesis
hypothesis = tf.matmul(X, W) + b # matrix간 곱셈

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 10 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  6082.3794 
Prediction:
 [[ 87.07887]
 [ 98.24527]
 [100.12691]
 [108.78618]
 [ 73.55441]]
10 Cost:  12.907193 
Prediction:
 [[155.98279]
 [181.08846]
 [181.7403 ]
 [197.66241]
 [136.74825]]
20 Cost:  12.784105 
Prediction:
 [[156.17769]
 [181.34845]
 [181.98311]
 [197.92812]
 [136.9519 ]]
30 Cost:  12.716937 
Prediction:
 [[156.16472]
 [181.35854]
 [181.97969]
 [197.9257 ]
 [136.96492]]
40 Cost:  12.650141 
Prediction:
 [[156.15117]
 [181.36786]
 [181.97559]
 [197.9225 ]
 [136.97734]]
50 Cost:  12.583696 
Prediction:
 [[156.13763]
 [181.37714]
 [181.97147]
 [197.9193 ]
 [136.98972]]
60 Cost:  12.51763 
Prediction:
 [[156.12416]
 [181.38641]
 [181.96736]
 [197.91612]
 [137.00206]]
70 Cost:  12.451891 
Prediction:
 [[156.11072]
 [181.39566]
 [181.96329]
 [197.91295]
 [137.01439]]
80 Cost:  12.3865185 
Prediction:
 [[156.0973 ]
 [181.40486]
 [181.95918]
 [197.90974]
 [137.02666]]
90 Cost:  12.3215475 
Prediction:
 [[156.08395]
 [181.41406]
 [181.95514]
 [197.9066 ]
 [137.03891]]


820 Cost:  8.4114485 
Prediction:
 [[155.20015]
 [182.02158]
 [181.68639]
 [197.6961 ]
 [137.84975]]
830 Cost:  8.367877 
Prediction:
 [[155.18921]
 [182.02908]
 [181.68307]
 [197.69348]
 [137.85979]]
840 Cost:  8.32457 
Prediction:
 [[155.17833]
 [182.03658]
 [181.67975]
 [197.69087]
 [137.8698 ]]
850 Cost:  8.281482 
Prediction:
 [[155.16747]
 [182.04405]
 [181.67647]
 [197.68828]
 [137.87979]]
860 Cost:  8.238605 
Prediction:
 [[155.15662]
 [182.05148]
 [181.67316]
 [197.68567]
 [137.88976]]
870 Cost:  8.195981 
Prediction:
 [[155.14581]
 [182.05891]
 [181.66988]
 [197.68307]
 [137.89969]]
880 Cost:  8.153589 
Prediction:
 [[155.13504]
 [182.06633]
 [181.6666 ]
 [197.6805 ]
 [137.90959]]
890 Cost:  8.111427 
Prediction:
 [[155.12428]
 [182.07372]
 [181.66333]
 [197.67792]
 [137.91946]]
900 Cost:  8.069492 
Prediction:
 [[155.11359]
 [182.08109]
 [181.66008]
 [197.67535]
 [137.92934]]
910 Cost:  8.027754 
Prediction:
 [[155.10289]
 [182.08844]
 [181.65683]
 [197.67278]
 [137.93916]]


1710 Cost:  5.3256555 
Prediction:
 [[154.33588]
 [182.61598]
 [181.42403]
 [197.48712]
 [138.64604]]
1720 Cost:  5.2987313 
Prediction:
 [[154.32733]
 [182.62189]
 [181.42142]
 [197.48505]
 [138.65396]]
1730 Cost:  5.2719145 
Prediction:
 [[154.31879]
 [182.62778]
 [181.41884]
 [197.48294]
 [138.66187]]
1740 Cost:  5.245289 
Prediction:
 [[154.31026]
 [182.63362]
 [181.41624]
 [197.48085]
 [138.66972]]
1750 Cost:  5.218824 
Prediction:
 [[154.30176]
 [182.63945]
 [181.41367]
 [197.47879]
 [138.67757]]
1760 Cost:  5.1924357 
Prediction:
 [[154.2933 ]
 [182.64532]
 [181.41113]
 [197.47673]
 [138.68542]]
1770 Cost:  5.1662846 
Prediction:
 [[154.28487]
 [182.65111]
 [181.40855]
 [197.47466]
 [138.6932 ]]
1780 Cost:  5.1401987 
Prediction:
 [[154.27643]
 [182.6569 ]
 [181.40598]
 [197.4726 ]
 [138.70099]]
1790 Cost:  5.1142626 
Prediction:
 [[154.268  ]
 [182.66267]
 [181.40343]
 [197.47054]
 [138.70876]]
1800 Cost:  5.088473 
Prediction:
 [[154.25966]
 [182.66847]
 [181.40091]
 [197.4685

In [4]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(207)  # for reproducibility

In [5]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)

In [7]:
xy

array([[ 73.,  80.,  75., 152.],
       [ 93.,  88.,  93., 185.],
       [ 89.,  91.,  90., 180.],
       [ 96.,  98., 100., 196.],
       [ 73.,  66.,  70., 142.],
       [ 53.,  46.,  55., 101.],
       [ 69.,  74.,  77., 149.],
       [ 47.,  56.,  60., 115.],
       [ 87.,  79.,  90., 175.],
       [ 79.,  70.,  88., 164.],
       [ 69.,  70.,  73., 141.],
       [ 70.,  65.,  74., 141.],
       [ 93.,  95.,  91., 184.],
       [ 79.,  80.,  73., 152.],
       [ 70.,  73.,  78., 148.],
       [ 93.,  89.,  96., 192.],
       [ 78.,  75.,  68., 147.],
       [ 81.,  90.,  93., 183.],
       [ 88.,  92.,  86., 177.],
       [ 78.,  83.,  77., 159.],
       [ 82.,  86.,  90., 177.],
       [ 86.,  82.,  89., 175.],
       [ 78.,  83.,  85., 175.],
       [ 76.,  83.,  71., 149.],
       [ 96.,  93.,  95., 192.]], dtype=float32)

In [8]:
x_data = xy[:, 0:-1] # 모든 행, 첫번째 열부터 마지막 전열까지 슬라이싱
y_data = xy[:, [-1]] # 모든 행, 마지막 열 슬라이싱

In [9]:
print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data)

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]]


In [10]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [11]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [12]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [13]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [14]:
for step in range(2001):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    if step % 20 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  13454.809 
Prediction:
 [[44.3339  ]
 [56.47901 ]
 [54.218163]
 [57.30488 ]
 [45.148777]
 [30.65668 ]
 [39.163303]
 [23.795328]
 [51.231133]
 [43.67121 ]
 [40.470985]
 [40.5446  ]
 [57.952587]
 [50.85206 ]
 [39.601242]
 [55.316082]
 [51.539635]
 [45.296875]
 [55.03422 ]
 [48.50626 ]
 [47.133575]
 [50.975353]
 [45.16224 ]
 [49.120224]
 [58.939484]]
20 Cost:  40.61873 
Prediction:
 [[153.20894]
 [187.34976]
 [183.15868]
 [197.75359]
 [144.94353]
 [104.26787]
 [144.32423]
 [101.79702]
 [173.56995]
 [157.03809]
 [141.76865]
 [140.44069]
 [191.14288]
 [161.54051]
 [145.25   ]
 [188.13957]
 [156.93228]
 [171.51161]
 [182.0065 ]
 [162.11893]
 [170.44524]
 [173.77103]
 [162.72261]
 [158.83865]
 [194.5591 ]]
40 Cost:  40.157703 
Prediction:
 [[153.19762]
 [187.34868]
 [183.14929]
 [197.76604]
 [144.92714]
 [104.29221]
 [144.36375]
 [101.86815]
 [173.59953]
 [157.1167 ]
 [141.78717]
 [140.47318]
 [191.11015]
 [161.48169]
 [145.29408]
 [188.15894]
 [156.85262]
 [171.57043]
 [181.96977]
 

640 Cost:  29.003786 
Prediction:
 [[152.79231]
 [187.12358]
 [182.74286]
 [197.92729]
 [144.32233]
 [104.80919]
 [145.30957]
 [103.71502]
 [174.18806]
 [159.02061]
 [142.15613]
 [141.18431]
 [190.07503]
 [159.7735 ]
 [146.35027]
 [188.48239]
 [154.57309]
 [173.02658]
 [180.84647]
 [161.16519]
 [171.41696]
 [174.15364]
 [163.44702]
 [156.9366 ]
 [193.98549]]
660 Cost:  28.707714 
Prediction:
 [[152.7815 ]
 [187.11595]
 [182.73111]
 [197.93231]
 [144.30318]
 [104.8232 ]
 [145.33832]
 [103.77111]
 [174.204  ]
 [159.07521]
 [142.16714]
 [141.20439]
 [190.0447 ]
 [159.7231 ]
 [146.38194]
 [188.49115]
 [154.50513]
 [173.0711 ]
 [180.81389]
 [161.1387 ]
 [171.44513]
 [174.16357]
 [163.46832]
 [156.88347]
 [193.96834]]
680 Cost:  28.415798 
Prediction:
 [[152.77081]
 [187.10835]
 [182.71948]
 [197.93732]
 [144.28407]
 [104.83702]
 [145.3669 ]
 [103.82689]
 [174.2197 ]
 [159.12932]
 [142.17807]
 [141.22424]
 [190.01462]
 [159.67311]
 [146.41339]
 [188.49982]
 [154.43764]
 [173.11537]
 [180.781

1380 Cost:  20.37644 
Prediction:
 [[152.48253]
 [186.84271]
 [182.37167]
 [198.09915]
 [143.65552]
 [105.21757]
 [146.2698 ]
 [105.58671]
 [174.65097]
 [160.7314 ]
 [142.51666]
 [141.80121]
 [189.1017 ]
 [158.1448 ]
 [147.39238]
 [188.73854]
 [152.35007]
 [174.52205]
 [179.81276]
 [160.33514]
 [172.351  ]
 [174.4474 ]
 [164.16536]
 [155.25586]
 [193.40773]]
1400 Cost:  20.198576 
Prediction:
 [[152.47643]
 [186.83522]
 [182.36328]
 [198.10342]
 [143.63869]
 [105.22587]
 [146.29301]
 [105.63192]
 [174.66034]
 [160.76974]
 [142.52519]
 [141.8147 ]
 [189.07924]
 [158.10687]
 [147.41716]
 [188.74377]
 [152.29756]
 [174.55844]
 [179.78923]
 [160.31653]
 [172.37343]
 [174.4535 ]
 [164.1829 ]
 [155.21773]
 [193.39363]]
1420 Cost:  20.023085 
Prediction:
 [[152.47041]
 [186.82773]
 [182.35493]
 [198.10768]
 [143.62192]
 [105.23404]
 [146.3161 ]
 [105.67685]
 [174.66956]
 [160.80772]
 [142.53366]
 [141.82803]
 [189.05695]
 [158.06921]
 [147.44179]
 [188.74892]
 [152.24542]
 [174.59464]
 [179.7

# Queue Runners

In [15]:
filename_queue = tf.train.string_input_producer(
    ['data-01-test-score.csv'], shuffle=False, name='filename_queue')

Instructions for updating:
To construct input pipelines, use the `tf.data` module.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.


In [16]:
reader = tf.TextLineReader()
key, value = reader.read(filename_queue)

In [17]:
record_defaults = [[0.], [0.], [0.], [0.]]
# record_dafaults 값을 통해 데이터의 type이 무엇인지 설정할 수 있음
xy = tf.decode_csv(value, record_defaults=record_defaults)

In [18]:
# collect batches of csv in
train_x_batch, train_y_batch = tf.train.batch([xy[0:-1], xy[-1:]], batch_size=10)
# batch 개념
## x data = xy[0:-1], y data = xy[-1:] 한번에 10개씩 

In [19]:
train_x_batch

<tf.Tensor 'batch:0' shape=(10, 3) dtype=float32>

In [20]:
train_y_batch

<tf.Tensor 'batch:1' shape=(10, 1) dtype=float32>

In [21]:
X = tf.placeholder(tf.float32, shape=[None, 3])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [22]:
W = tf.Variable(tf.random_normal([3, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [23]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

# Minimize
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [24]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())


In [25]:
# Start populating the filename queue.
coord = tf.train.Coordinator()
threads = tf.train.start_queue_runners(sess=sess, coord=coord)

Instructions for updating:
To construct input pipelines, use the `tf.data` module.


In [26]:
for step in range(2001):
    x_batch, y_batch = sess.run([train_x_batch, train_y_batch])
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_batch, Y: y_batch})
    if step % 20 == 0:
        print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  8225.208 
Prediction:
 [[79.18648 ]
 [78.87869 ]
 [86.22125 ]
 [90.5189  ]
 [59.2849  ]
 [37.35105 ]
 [67.89143 ]
 [50.82236 ]
 [66.204575]
 [52.909786]]
20 Cost:  105.90178 
Prediction:
 [[162.82532]
 [179.56755]
 [185.34412]
 [198.51582]
 [136.0802 ]
 [ 94.0569 ]
 [148.75156]
 [110.79122]
 [160.39772]
 [140.26865]]
40 Cost:  103.97179 
Prediction:
 [[162.74663 ]
 [179.61818 ]
 [185.31583 ]
 [198.52591 ]
 [136.12112 ]
 [ 94.167145]
 [148.77919 ]
 [110.83549 ]
 [160.52866 ]
 [140.4933  ]]
60 Cost:  102.10777 
Prediction:
 [[162.66489 ]
 [179.66377 ]
 [185.28326 ]
 [198.53098 ]
 [136.15822 ]
 [ 94.273834]
 [148.80287 ]
 [110.87662 ]
 [160.65414 ]
 [140.71199 ]]
80 Cost:  100.277916 
Prediction:
 [[162.58386 ]
 [179.70898 ]
 [185.25105 ]
 [198.53606 ]
 [136.19499 ]
 [ 94.379555]
 [148.82637 ]
 [110.91734 ]
 [160.77853 ]
 [140.92871 ]]
100 Cost:  98.4821 
Prediction:
 [[162.50356 ]
 [179.75375 ]
 [185.21909 ]
 [198.54102 ]
 [136.23143 ]
 [ 94.484314]
 [148.84961 ]
 [110.957664]
 

980 Cost:  45.06394 
Prediction:
 [[159.60211]
 [181.37709]
 [184.06754]
 [198.71928]
 [137.55765]
 [ 98.26898]
 [149.67874]
 [112.39392]
 [165.35431]
 [148.89047]]
1000 Cost:  44.28905 
Prediction:
 [[159.54866 ]
 [181.40712 ]
 [184.04637 ]
 [198.72253 ]
 [137.58229 ]
 [ 98.338684]
 [149.6938  ]
 [112.41991 ]
 [165.43633 ]
 [149.03293 ]]
1020 Cost:  43.528633 
Prediction:
 [[159.49568]
 [181.43686]
 [184.02539]
 [198.72572]
 [137.6067 ]
 [ 98.40775]
 [149.70866]
 [112.44564]
 [165.51758]
 [149.17409]]
1040 Cost:  42.782433 
Prediction:
 [[159.44318 ]
 [181.46632 ]
 [184.00461 ]
 [198.72888 ]
 [137.6309  ]
 [ 98.476204]
 [149.7234  ]
 [112.47112 ]
 [165.5981  ]
 [149.31395 ]]
1060 Cost:  42.05001 
Prediction:
 [[159.39114 ]
 [181.49554 ]
 [183.98404 ]
 [198.73201 ]
 [137.6549  ]
 [ 98.54404 ]
 [149.73799 ]
 [112.496346]
 [165.67793 ]
 [149.45256 ]]
1080 Cost:  41.33135 
Prediction:
 [[159.33958 ]
 [181.5245  ]
 [183.96365 ]
 [198.73512 ]
 [137.67868 ]
 [ 98.61125 ]
 [149.75243 ]
 [112.

 [154.63683 ]]
2000 Cost:  19.453257 
Prediction:
 [[157.40714]
 [182.61392]
 [183.20137]
 [198.84952]
 [138.5779 ]
 [101.12964]
 [150.28474]
 [113.43966]
 [168.7203 ]
 [154.72713]]


In [27]:
coord.request_stop()
coord.join(threads)

# Sigmoid
## g(z) = 1/(1+e^-z)
- z = WX
- H(X) = g(z)

## logistic hypothesis
- H(X) = 1/(1+e^-W^T*X)

- cost function = -y(log(H(x)) - (1-y)log(1-H(x))
- ex) y=1 -> -log(H(x))
- ex) y=0 -> -log(1-H(x))

In [29]:
import tensorflow as tf
tf.set_random_seed(207)  # for reproducibility

x_data = [[1, 2],
          [2, 3],
          [3, 1],
          [4, 3],
          [5, 3],
          [6, 2]]
y_data = [[0],
          [0],
          [0],
          [1],
          [1],
          [1]]

In [30]:
# placeholders for a tensor that will be always fed.
X = tf.placeholder(tf.float32, shape=[None, 2])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [31]:
W = tf.Variable(tf.random_normal([2, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [32]:
# Hypothesis using sigmoid: tf.div(1., 1. + tf.exp(tf.matmul(X, W)))
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

In [33]:
# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

In [34]:
# Accuracy computation
# True if hypothesis>0.5 else False
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [35]:
predicted

<tf.Tensor 'Cast:0' shape=(?, 1) dtype=float32>

In [37]:
accuracy

<tf.Tensor 'Mean_5:0' shape=() dtype=float32>

In [38]:
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, cost_val)

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect (Y): ", c, "\nAccuracy: ", a)

0 0.9231817
200 0.5734833
400 0.53339654
600 0.5056483
800 0.483614
1000 0.46462548
1200 0.44749808
1400 0.43166327
1600 0.41682842
1800 0.40283158
2000 0.38957557
2200 0.37699565
2400 0.36504444
2600 0.35368332
2800 0.34287894
3000 0.33260095
3200 0.3228208
3400 0.31351152
3600 0.30464742
3800 0.29620394
4000 0.2881577
4200 0.28048655
4400 0.2731693
4600 0.2661859
4800 0.25951755
5000 0.2531464
5200 0.24705566
5400 0.24122936
5600 0.2356528
5800 0.23031203
6000 0.22519396
6200 0.22028624
6400 0.21557741
6600 0.21105672
6800 0.20671387
7000 0.20253958
7200 0.19852489
7400 0.19466132
7600 0.1909412
7800 0.18735714
8000 0.18390228
8200 0.18057005
8400 0.17735453
8600 0.17424989
8800 0.1712507
9000 0.16835207
9200 0.16554914
9400 0.16283743
9600 0.16021283
9800 0.15767132
10000 0.15520908

Hypothesis:  [[0.0331798 ]
 [0.16202655]
 [0.31633535]
 [0.7761914 ]
 [0.9362567 ]
 [0.9790618 ]] 
Correct (Y):  [[0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]] 
Accuracy:  1.0


In [39]:
import tensorflow as tf
import numpy as np
tf.set_random_seed(207)  # for reproducibility

In [40]:
xy = np.loadtxt('data-03-diabetes.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [41]:
print(x_data.shape, y_data.shape)

(759, 8) (759, 1)


In [42]:
X = tf.placeholder(tf.float32, shape=[None, 8])
Y = tf.placeholder(tf.float32, shape=[None, 1])

In [43]:
W = tf.Variable(tf.random_normal([8, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [44]:
hypothesis = tf.sigmoid(tf.matmul(X, W) + b)

In [45]:
# cost/loss function
cost = -tf.reduce_mean(Y * tf.log(hypothesis) + (1 - Y) * tf.log(1 - hypothesis))

train = tf.train.GradientDescentOptimizer(learning_rate=0.01).minimize(cost)

In [46]:
predicted = tf.cast(hypothesis > 0.5, dtype=tf.float32)
accuracy = tf.reduce_mean(tf.cast(tf.equal(predicted, Y), dtype=tf.float32))

In [47]:
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(10001):
        cost_val, _ = sess.run([cost, train], feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, cost_val)

    # Accuracy report
    h, c, a = sess.run([hypothesis, predicted, accuracy],
                       feed_dict={X: x_data, Y: y_data})
    print("\nHypothesis: ", h, "\nCorrect (Y): ", c, "\nAccuracy: ", a)

0 0.7689952
200 0.6377029
400 0.5934052
600 0.5770993
800 0.5675631
1000 0.5599381
1200 0.55324024
1400 0.5472279
1600 0.5417988
1800 0.53688174
2000 0.53241813
2200 0.52835757
2400 0.52465576
2600 0.52127415
2800 0.5181789
3000 0.5153402
3200 0.512732
3400 0.51033133
3600 0.5081177
3800 0.50607306
4000 0.5041817
4200 0.50242925
4400 0.500803
4600 0.4992919
4800 0.49788576
5000 0.49657547
5200 0.49535307
5400 0.4942112
5600 0.4931432
5800 0.4921433
6000 0.49120602
6200 0.4903265
6400 0.4895003
6600 0.48872343
6800 0.48799235
7000 0.48730364
7200 0.48665416
7400 0.48604134
7600 0.48546234
7800 0.48491508
8000 0.48439726
8200 0.4839071
8400 0.48344257
8600 0.48300207
8800 0.48258403
9000 0.48218703
9200 0.4818098
9400 0.48145115
9600 0.48110986
9800 0.48078486
10000 0.48047528

Hypothesis:  [[0.4037604 ]
 [0.92460996]
 [0.24504833]
 [0.93880326]
 [0.20012833]
 [0.767062  ]
 [0.9443534 ]
 [0.6273864 ]
 [0.23866084]
 [0.51010305]
 [0.6875607 ]
 [0.18174957]
 [0.26494643]
 [0.26573783]
 [0.

## SoftMax clssification / Multinomial classification
- logistic cost = cross entropy

In [49]:
import tensorflow as tf

In [50]:
tf.set_random_seed(207)  # for reproducibility

In [51]:
x_data = [[1, 2, 1, 1],
          [2, 1, 3, 2],
          [3, 1, 3, 4],
          [4, 1, 5, 5],
          [1, 7, 5, 5],
          [1, 2, 5, 6],
          [1, 6, 6, 6],
          [1, 7, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [52]:
X = tf.placeholder("float", [None, 4])
Y = tf.placeholder("float", [None, 3])
nb_classes = 3

In [53]:
W = tf.Variable(tf.random_normal([4, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

In [54]:
# tf.nn.softmax computes softmax activations
# softmax = exp(logits) / reduce_sum(exp(logits), dim)
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

In [55]:
# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))

optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [56]:
# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))

    print('--------------')

0 1.8809056
200 0.5702704
400 0.4627792
600 0.36689627
800 0.27634877
1000 0.2329536
1200 0.21114942
1400 0.19301485
1600 0.17767808
1800 0.16453645
2000 0.1531524
--------------


In [57]:
# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2001):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 200 == 0:
            print(step, sess.run(cost, feed_dict={X: x_data, Y: y_data}))

    print('--------------')

    # Testing & One-hot encoding
    a = sess.run(hypothesis, feed_dict={X: [[1, 11, 7, 9]]})
    print(a, sess.run(tf.argmax(a, 1)))

    print('--------------')

    b = sess.run(hypothesis, feed_dict={X: [[1, 3, 4, 3]]})
    print(b, sess.run(tf.argmax(b, 1)))

    print('--------------')

    c = sess.run(hypothesis, feed_dict={X: [[1, 1, 0, 1]]})
    print(c, sess.run(tf.argmax(c, 1)))

    print('--------------')

    all = sess.run(hypothesis, feed_dict={
                   X: [[1, 11, 7, 9], [1, 3, 4, 3], [1, 1, 0, 1]]})
    print(all, sess.run(tf.argmax(all, 1)))

0 1.8809056
200 0.5702704
400 0.4627792
600 0.36689627
800 0.27634877
1000 0.2329536
1200 0.21114942
1400 0.19301485
1600 0.17767808
1800 0.16453645
2000 0.1531524
--------------
[[6.609248e-03 9.933814e-01 9.301384e-06]] [1]
--------------
[[0.83486986 0.14878257 0.01634759]] [0]
--------------
[[9.9196473e-09 3.3119685e-04 9.9966884e-01]] [2]
--------------
[[6.6092480e-03 9.9338138e-01 9.3013841e-06]
 [8.3486986e-01 1.4878257e-01 1.6347587e-02]
 [9.9196473e-09 3.3119685e-04 9.9966884e-01]] [1 0 2]


In [58]:
import tensorflow as tf
import numpy as np

In [59]:
tf.set_random_seed(207)  # for reproducibility

In [60]:
xy = np.loadtxt('data-04-zoo.csv', delimiter=',', dtype=np.float32)
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [61]:
print(x_data.shape, y_data.shape)

(101, 16) (101, 1)


In [63]:
nb_classes = 7  # 0 ~ 6

In [64]:
X = tf.placeholder(tf.float32, [None, 16])
Y = tf.placeholder(tf.int32, [None, 1])  # 0 ~ 6
Y_one_hot = tf.one_hot(Y, nb_classes)  # one hot
print("one_hot", Y_one_hot)

one_hot Tensor("one_hot:0", shape=(?, 1, 7), dtype=float32)


In [65]:
Y_one_hot = tf.reshape(Y_one_hot, [-1, nb_classes])
print("reshape", Y_one_hot)

reshape Tensor("Reshape:0", shape=(?, 7), dtype=float32)


In [66]:
W = tf.Variable(tf.random_normal([16, nb_classes]), name='weight')
b = tf.Variable(tf.random_normal([nb_classes]), name='bias')

In [67]:
logits = tf.matmul(X, W) + b
hypothesis = tf.nn.softmax(logits)

In [69]:
# Cross entropy cost/loss
cost_i = tf.nn.softmax_cross_entropy_with_logits_v2(logits=logits,
                                                 labels=tf.stop_gradient([Y_one_hot]))
cost = tf.reduce_mean(cost_i)
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [70]:
prediction = tf.argmax(hypothesis, 1)
correct_prediction = tf.equal(prediction, tf.argmax(Y_one_hot, 1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32))

In [71]:
# Launch graph
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())

    for step in range(2000):
        sess.run(optimizer, feed_dict={X: x_data, Y: y_data})
        if step % 100 == 0:
            loss, acc = sess.run([cost, accuracy], feed_dict={
                                 X: x_data, Y: y_data})
            print("Step: {:5}\tLoss: {:.3f}\tAcc: {:.2%}".format(
                step, loss, acc))

    # Let's see if we can predict
    pred = sess.run(prediction, feed_dict={X: x_data})
    # y_data: (N,1) = flatten => (N, ) matches pred.shape
    for p, y in zip(pred, y_data.flatten()):
        print("[{}] Prediction: {} True Y: {}".format(p == int(y), p, int(y)))

Step:     0	Loss: 3.483	Acc: 17.82%
Step:   100	Loss: 0.479	Acc: 90.10%
Step:   200	Loss: 0.330	Acc: 91.09%
Step:   300	Loss: 0.261	Acc: 95.05%
Step:   400	Loss: 0.217	Acc: 95.05%
Step:   500	Loss: 0.186	Acc: 96.04%
Step:   600	Loss: 0.162	Acc: 96.04%
Step:   700	Loss: 0.143	Acc: 97.03%
Step:   800	Loss: 0.128	Acc: 99.01%
Step:   900	Loss: 0.115	Acc: 99.01%
Step:  1000	Loss: 0.104	Acc: 99.01%
Step:  1100	Loss: 0.095	Acc: 99.01%
Step:  1200	Loss: 0.088	Acc: 99.01%
Step:  1300	Loss: 0.081	Acc: 99.01%
Step:  1400	Loss: 0.076	Acc: 99.01%
Step:  1500	Loss: 0.071	Acc: 99.01%
Step:  1600	Loss: 0.066	Acc: 100.00%
Step:  1700	Loss: 0.063	Acc: 100.00%
Step:  1800	Loss: 0.059	Acc: 100.00%
Step:  1900	Loss: 0.056	Acc: 100.00%
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 0 True Y: 0
[True] Prediction: 3 True Y: 3
[True] Prediction: 3 True Y:

# Tips
## Learning rate
- large learning rate = overshooting
- small learning rate = takes too long, stops at local minimum
##### try several learning rates

## Preprocessing for gradient descent
##### standardization
###### x_std[:,0] = (x[:,0] - x[:,0].mean()) / x[:,0].std()
- zero-centered 
- normalized

## Overfitting
##### model is very good at training data set
##### not good at test dataset or in real use
###### Solution
- more training data
- reduce the number of features
- regularization(lambda_ 0~1)
  not have too big numbers in the weight
  l2reg = lambda * tf.reduce_sum(tf.square(W))

In [72]:
import tensorflow as tf

In [73]:
tf.set_random_seed(207)  # for reproducibility

In [74]:
x_data = [[1, 2, 1],
          [1, 3, 2],
          [1, 3, 4],
          [1, 5, 5],
          [1, 7, 5],
          [1, 2, 5],
          [1, 6, 6],
          [1, 7, 7]]
y_data = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1],
          [0, 1, 0],
          [0, 1, 0],
          [0, 1, 0],
          [1, 0, 0],
          [1, 0, 0]]

In [76]:
# Evaluation our model using this test dataset
x_test = [[2, 1, 1],
          [3, 1, 2],
          [3, 3, 4]]
y_test = [[0, 0, 1],
          [0, 0, 1],
          [0, 0, 1]]

In [77]:
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

In [78]:
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

In [85]:
# Cross entropy cost/loss
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
# Try to change learning_rate to small numbers
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

# Correct prediction Test model
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [86]:
# Launch graph
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())

    for step in range(201):
        cost_val, W_val, _ = sess.run(
            [cost, W, optimizer], feed_dict={X: x_data, Y: y_data})
        print(step, cost_val, W_val)

    # predict
    print("Prediction:", sess.run(prediction, feed_dict={X: x_test}))
    # Calculate the accuracy
    print("Accuracy: ", sess.run(accuracy, feed_dict={X: x_test, Y: y_test}))

0 4.5538235 [[ 0.23440658  0.9135212  -0.33029255]
 [-1.5045515   0.512041    0.66804045]
 [ 1.5521199   0.52548254  0.31286165]]
1 2.70496 [[ 0.25148508  0.87193483 -0.3057847 ]
 [-1.358829    0.32486287  0.709496  ]
 [ 1.6768034   0.36611474  0.34754592]]
2 2.1213055 [[ 0.26039162  0.87244374 -0.31520012]
 [-1.234847    0.35081726  0.5595596 ]
 [ 1.7647744   0.41778713  0.20790239]]
3 1.7811532 [[ 0.26311433  0.8476927  -0.2931718 ]
 [-1.1367778   0.22760305  0.58470464]
 [ 1.8234046   0.3364719   0.2305876 ]]
4 1.6319137 [[ 0.25128278  0.85144746 -0.285095  ]
 [-1.1115913   0.25768197  0.5294393 ]
 [ 1.8061641   0.3997016   0.18459833]]
5 1.5833381 [[ 0.24094452  0.84189576 -0.26520506]
 [-1.0800318   0.21315067  0.542411  ]
 [ 1.7960635   0.39561892  0.19878164]]
6 1.5532216 [[ 0.22762753  0.83996546 -0.24995777]
 [-1.0645512   0.21058458  0.52949667]
 [ 1.7698673   0.42950752  0.19108924]]
7 1.5270414 [[ 0.21660654  0.8338535  -0.23282479]
 [-1.0373468   0.18484658  0.5280303 ]
 [

92 0.7606009 [[-0.5082963   0.5497671   0.77616453]
 [-0.12186545 -0.25712582  0.05452201]
 [ 1.1341836   1.0006747   0.25560513]]
93 0.75805414 [[-0.51431185  0.547337    0.78461015]
 [-0.11892323 -0.25622258  0.05067653]
 [ 1.1335311   1.0008523   0.25608006]]
94 0.7555456 [[-0.5202946   0.54493254  0.79299736]
 [-0.11604326 -0.25530317  0.04687716]
 [ 1.1329304   1.0010076   0.2565256 ]]
95 0.753075 [[-0.5262451   0.54255366  0.80132675]
 [-0.11322403 -0.25436893  0.04312369]
 [ 1.1323798   1.001142    0.2569418 ]]
96 0.75064117 [[-0.5321638   0.5402002   0.8095989 ]
 [-0.11046359 -0.2534216   0.03941593]
 [ 1.131878    1.0012567   0.2573288 ]]
97 0.74824315 [[-0.53805125  0.5378721   0.81781447]
 [-0.10776064 -0.2524622   0.03575358]
 [ 1.1314235   1.0013534   0.2576867 ]]
98 0.74588066 [[-0.5439079   0.53556913  0.82597405]
 [-0.10511328 -0.2514924   0.03213644]
 [ 1.1310152   1.0014328   0.25801563]]
99 0.7435524 [[-0.54973423  0.53329134  0.8340782 ]
 [-0.10252045 -0.25051302  0

 [ 1.1709141e+00  9.9674207e-01  2.2280696e-01]]
172 0.63257205 [[-9.1529697e-01  4.2356554e-01  1.3093666e+00]
 [-4.9504021e-04 -1.8795906e-01 -1.3601503e-01]
 [ 1.1719683e+00  9.9669379e-01  2.2180092e-01]]
173 0.63155496 [[-9.1970128e-01  4.2267683e-01  1.3146596e+00]
 [ 1.9522925e-04 -1.8735290e-01 -1.3731146e-01]
 [ 1.1730293e+00  9.9664629e-01  2.2078748e-01]]
174 0.6305462 [[-9.2409343e-01  4.2180079e-01  1.3199278e+00]
 [ 8.7434374e-04 -1.8675283e-01 -1.3859063e-01]
 [ 1.1740966e+00  9.9659967e-01  2.1976689e-01]]
175 0.62954557 [[-0.92847353  0.42093727  1.3251715 ]
 [ 0.00154264 -0.18615893 -0.13985284]
 [ 1.1751701   0.9965538   0.21873933]]
176 0.6285529 [[-0.9328418   0.42008615  1.3303908 ]
 [ 0.00220017 -0.18557096 -0.14109834]
 [ 1.1762495   0.99650866  0.21770498]]
177 0.6275683 [[-0.9371982   0.4192473   1.3355861 ]
 [ 0.00284725 -0.18498898 -0.14232738]
 [ 1.1773349   0.9964642   0.21666406]]
178 0.62659144 [[-0.941543    0.4184206   1.3407576 ]
 [ 0.00348392 -0.1844

## min_max normalization

In [87]:
import numpy as np
tf.set_random_seed(207)  # for reproducibility

In [88]:
def MinMaxScaler(data):
    numerator = data - np.min(data, 0)
    denominator = np.max(data, 0) - np.min(data, 0)
    # noise term prevents the zero division
    return numerator / (denominator + 1e-7)

In [89]:
xy = np.array([[828.659973, 833.450012, 908100, 828.349976, 831.659973],
               [823.02002, 828.070007, 1828100, 821.655029, 828.070007],
               [819.929993, 824.400024, 1438100, 818.97998, 824.159973],
               [816, 820.958984, 1008100, 815.48999, 819.23999],
               [819.359985, 823, 1188100, 818.469971, 818.97998],
               [819, 823, 1198100, 816, 820.450012],
               [811.700012, 815.25, 1098100, 809.780029, 813.669983],
               [809.51001, 816.659973, 1398100, 804.539978, 809.559998]])

In [90]:
xy = MinMaxScaler(xy)
print(xy)

[[0.99999999 0.99999999 0.         1.         1.        ]
 [0.70548491 0.70439552 1.         0.71881782 0.83755791]
 [0.54412549 0.50274824 0.57608696 0.606468   0.6606331 ]
 [0.33890353 0.31368023 0.10869565 0.45989134 0.43800918]
 [0.51436    0.42582389 0.30434783 0.58504805 0.42624401]
 [0.49556179 0.42582389 0.31521739 0.48131134 0.49276137]
 [0.11436064 0.         0.20652174 0.22007776 0.18597238]
 [0.         0.07747099 0.5326087  0.         0.        ]]


In [91]:
x_data = xy[:, 0:-1]
y_data = xy[:, [-1]]

In [92]:
X = tf.placeholder(tf.float32, shape=[None, 4])
Y = tf.placeholder(tf.float32, shape=[None, 1])

W = tf.Variable(tf.random_normal([4, 1]), name='weight')
b = tf.Variable(tf.random_normal([1]), name='bias')

In [93]:
# Hypothesis
hypothesis = tf.matmul(X, W) + b

# Simplified cost/loss function
cost = tf.reduce_mean(tf.square(hypothesis - Y))

In [94]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=1e-5)
train = optimizer.minimize(cost)

In [95]:
# Launch the graph in a session.
sess = tf.Session()
# Initializes global variables in the graph.
sess.run(tf.global_variables_initializer())

In [96]:
for step in range(101):
    cost_val, hy_val, _ = sess.run(
        [cost, hypothesis, train], feed_dict={X: x_data, Y: y_data})
    print(step, "Cost: ", cost_val, "\nPrediction:\n", hy_val)

0 Cost:  0.23752882 
Prediction:
 [[0.8179967 ]
 [0.15231264]
 [0.45693135]
 [0.8663672 ]
 [0.61730325]
 [0.692598  ]
 [0.78480536]
 [0.8587898 ]]
1 Cost:  0.2375277 
Prediction:
 [[0.8179962 ]
 [0.15231156]
 [0.4569298 ]
 [0.8663652 ]
 [0.6173016 ]
 [0.6925962 ]
 [0.7848027 ]
 [0.858787  ]]
2 Cost:  0.23752658 
Prediction:
 [[0.8179957 ]
 [0.15231049]
 [0.4569283 ]
 [0.86636317]
 [0.6172999 ]
 [0.6925944 ]
 [0.78479993]
 [0.85878414]]
3 Cost:  0.23752543 
Prediction:
 [[0.81799525]
 [0.15230942]
 [0.4569267 ]
 [0.8663611 ]
 [0.61729825]
 [0.6925926 ]
 [0.78479725]
 [0.8587813 ]]
4 Cost:  0.23752435 
Prediction:
 [[0.8179948 ]
 [0.15230823]
 [0.45692515]
 [0.866359  ]
 [0.6172965 ]
 [0.69259083]
 [0.7847945 ]
 [0.8587785 ]]
5 Cost:  0.23752323 
Prediction:
 [[0.8179943 ]
 [0.15230715]
 [0.45692366]
 [0.86635697]
 [0.61729485]
 [0.6925891 ]
 [0.7847918 ]
 [0.8587756 ]]
6 Cost:  0.23752207 
Prediction:
 [[0.8179938 ]
 [0.1523062 ]
 [0.45692205]
 [0.8663549 ]
 [0.6172931 ]
 [0.69258726]
 

## MNIST Dataset

In [97]:
import tensorflow as tf
import random
import matplotlib.pyplot as plt

In [98]:
tf.set_random_seed(207)  # for reproducibility

In [100]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use urllib or similar directly.
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py fr

In [101]:
nb_classes = 10

In [102]:
# MNIST data image of shape 28 * 28 = 784
X = tf.placeholder(tf.float32, [None, 784])
# 0 - 9 digits recognition = 10 classes
Y = tf.placeholder(tf.float32, [None, nb_classes])

In [103]:
W = tf.Variable(tf.random_normal([784, nb_classes]))
b = tf.Variable(tf.random_normal([nb_classes]))

In [104]:
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)

In [105]:
cost = tf.reduce_mean(-tf.reduce_sum(Y * tf.log(hypothesis), axis=1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1).minimize(cost)

In [106]:
# Test model
is_correct = tf.equal(tf.arg_max(hypothesis, 1), tf.arg_max(Y, 1))
# Calculate accuracy
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

In [107]:
# batch = 한번에 몇개를 학습시킬것인가
# epoch = 전체 데이터 셋을 한번 다 학습 시키면 1 epoch
## one epoch = one forward pass and one backward pass of all the training examples
## ex) 1000 training examples, 500 batch size -> 2 iterations to complete 1 epoch

In [108]:
# parameters
training_epochs = 15
batch_size = 100

In [109]:
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    # Training cycle
    for epoch in range(training_epochs):
        avg_cost = 0
        total_batch = int(mnist.train.num_examples / batch_size)

        for i in range(total_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            c, _ = sess.run([cost, optimizer], feed_dict={
                            X: batch_xs, Y: batch_ys})
            avg_cost += c / total_batch

        print('Epoch:', '%04d' % (epoch + 1),
              'cost =', '{:.9f}'.format(avg_cost))


Epoch: 0001 cost = 2.655475984
Epoch: 0002 cost = 1.100327535
Epoch: 0003 cost = 0.884214596
Epoch: 0004 cost = 0.774577536
Epoch: 0005 cost = 0.703630522
Epoch: 0006 cost = 0.653850219
Epoch: 0007 cost = 0.616161202
Epoch: 0008 cost = 0.585906959
Epoch: 0009 cost = 0.561567573
Epoch: 0010 cost = 0.541040046
Epoch: 0011 cost = 0.522825872
Epoch: 0012 cost = 0.507810413
Epoch: 0013 cost = 0.494943801
Epoch: 0014 cost = 0.483021189
Epoch: 0015 cost = 0.472379093


In [110]:
with tf.Session() as sess:
    # Initialize TensorFlow variables
    sess.run(tf.global_variables_initializer())
    # Training cycle
    for epoch in range(training_epochs):
        avg_cost = 0
        total_batch = int(mnist.train.num_examples / batch_size)

        for i in range(total_batch):
            batch_xs, batch_ys = mnist.train.next_batch(batch_size)
            c, _ = sess.run([cost, optimizer], feed_dict={
                            X: batch_xs, Y: batch_ys})
            avg_cost += c / total_batch

        print('Epoch:', '%04d' % (epoch + 1),
              'cost =', '{:.9f}'.format(avg_cost))

    print("Learning finished")

    # Test the model using test sets
    print("Accuracy: ", accuracy.eval(session=sess, feed_dict={
          X: mnist.test.images, Y: mnist.test.labels}))


Epoch: 0001 cost = 2.657713238
Epoch: 0002 cost = 1.100082523
Epoch: 0003 cost = 0.884544228
Epoch: 0004 cost = 0.774006394
Epoch: 0005 cost = 0.703982936
Epoch: 0006 cost = 0.653432555
Epoch: 0007 cost = 0.616201660
Epoch: 0008 cost = 0.586375510
Epoch: 0009 cost = 0.561502937
Epoch: 0010 cost = 0.540726114
Epoch: 0011 cost = 0.523106415
Epoch: 0012 cost = 0.508145275
Epoch: 0013 cost = 0.494591231
Epoch: 0014 cost = 0.482834891
Epoch: 0015 cost = 0.472226450
Learning finished
Accuracy:  0.8901
